erDiagram
  especies {
    uuid    id PK
    text    nome_cientifico UK
    text[]  caracteristicas
    text    foto_url
    text    observacoes
    boolean ativa
  }
  especies_nomes_populares {
    uuid    id PK
    uuid    especie_id FK
    text    nome
    boolean e_principal
  }
  especies_fotos {
    uuid  id PK
    text  tipo_conteudo
    bytea conteudo
  }
  lotes {}
  pedidos_itens {}
  atribuicoes {}

  especies ||--o{ especies_nomes_populares : "e conhecida por"
  especies ||--o| especies_fotos           : "e ilustrada por"
  especies ||--o{ lotes                    : "e plantada em"
  especies ||--o{ pedidos_itens            : "e vendida em"
  especies ||--o{ atribuicoes              : "e objeto de"
