erDiagram
  PESSOA       ||--o{ PAPEL       : "exerce"
  PESSOA       ||--o{ ENDERECO    : "reside em"
  PESSOA       ||--o{ PEDIDO      : "faz como cliente"
  PEDIDO       ||--o{ ITEM_PEDIDO : "compoe-se de"
  ESPECIE      ||--o{ ITEM_PEDIDO : "e vendida em"
  RECIPIENTE   ||--o{ ITEM_PEDIDO : "define porte de"
  LOTE         ||--o{ ITEM_PEDIDO : "da saldo a"
  USUARIO      ||--o{ PEDIDO      : "registra"
  PESSOA       ||--o| USUARIO     : "pode ter login"
