erDiagram
  lotes_etapas {
    uuid        lote_id PK
    uuid        protocolo_etapa_id PK
    date        data_ancora
    date        ultima_execucao_em
    int         ocorrencias
    timestamptz concluido_em
    uuid        herdado_do_lote_id FK
  }
  lotes {}
  protocolos_etapas {}
  atribuicoes {}

  lotes             ||--o{ lotes_etapas : "percorre"
  protocolos_etapas ||--o{ lotes_etapas : "materializa-se em"
  lotes_etapas      ||--o{ atribuicoes  : "sugere"
