erDiagram
  areas {
    uuid id PK
    char letra UK
    text nome
  }
  canteiros {
    uuid id PK
    uuid area_id FK
    int  numero
    int  capacidade
  }
  turnos_trabalho {
    uuid    id PK
    text    nome UK
    time    inicio
    time    fim
    boolean ativo
  }
  lotes {}
  atribuicoes {}

  areas    ||--o{ canteiros   : "contem"
  canteiros||--o{ lotes       : "abriga"
  turnos_trabalho ||--o{ atribuicoes : "situa"
